# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Daily pipeline 

on:
  workflow_dispatch: {}
  schedule:
    # 北京时间早上11点 (UTC+8)
    - cron: '0 3 * * *'  # UTC时间3点 = 北京时间11点
  workflow_dispatch:

jobs:
  generate_and_send_digest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
      - name: Generate digest
        env:
          DASHSCOPE_API_KEY: ${{ secrets.DASHSCOPE_API_KEY }}
          DASHSCOPE_API_BASE: ${{ secrets.DASHSCOPE_API_BASE }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        run: python src/action.py
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: digest
          path: digest.html
    - name: check
      id: check
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        MAIL_CONNECTION: ${{ secrets.MAIL_CONNECTION }}
      if: "${{ env.SENDGRID_API_KEY == '' && (env.MAIL_CONNECTION || env.MAIL_USERNAME != '' && env.MAIL_PASSWORD != '') }}"
      run: echo "DEFINED=true" >> $GITHUB_OUTPUT 
    - name: Send mail
      uses: dawidd6/action-send-mail@v4
      env:
        DEFINED: ${{ steps.check.outputs.DEFINED }}
      if: ${{ env.DEFINED == 'true' }}
      with:
        # Specify connection via URL (replaces server_address, server_port, secure,
        # username and password)
        #
        # Format:
        #
        #  * smtp://user:password@server:port
        #  * smtp+starttls://user:password@server:port
        server_address: smtp.163.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        secure: true
        subject: Personalized arXiv Digest 
        to: ${{ secrets.TO_EMAIL }} 
        from: "Personalized arxiv digest" 
        html_body: file://digest.html
        ignore_cert: true
        convert_markdown: true
        priority: normal 
